#!/usr/bin/env bash
# ssh client configuration

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    Hostname 54.145.84.14
    User ubuntu
